#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Build a RWLT subset focused on the most TTFT-discrepant trajectories.

Given a per-turn diff TSV from ``diff_rwlt_runs.py`` and a value of K, this
script ranks conversations by a discrepancy metric, filters the source RWLT
JSONL to keep only the top-K conversations (preserving turn order), and writes
a matching RWLT config that points to the filtered file.

Usage:
    python3 scripts/make_topk_subset.py \\
        --diff rwlt-results/diff_round1_0521.tsv \\
        --k 5 \\
        --metric median_abs_delta \\
        --label round1_top5_median

That call writes:
    configs/datasets/round1_top5_median.jsonl
    configs/rwlt_round1_top5_median.yaml

Then run with run_session.sh just like rwlt_baseline:
    scripts/run_session.sh agg rwlt_round1_top5_median agg_round1_top5_median

Available metrics (computed per conversation across its turns):
    median_abs_delta    median(|ttft_disagg_ms - ttft_agg_ms|)        [default]
    sum_abs_delta       sum(|ttft_disagg_ms - ttft_agg_ms|)           biggest wallclock contributors
    mean_abs_delta      mean(|ttft_disagg_ms - ttft_agg_ms|)
    p99_abs_delta       99th percentile of |delta|                    worst-case turns
    max_abs_delta       max(|delta|)                                  single worst turn
    median_delta        median(ttft_disagg_ms - ttft_agg_ms)          signed; biggest disagg slowdown
"""
from __future__ import annotations

import argparse
import csv
import json
import statistics
import sys
from collections import defaultdict
from pathlib import Path

DEFAULT_SOURCE = Path(
    "/home/scratch.shobhitv_coreai/aa-rwlt-shared-datasets/aa-rwlt_coding-agent-scenario_tuning_v2.jsonl"
)


def _percentile(xs: list[float], q: float) -> float:
    if not xs:
        return float("nan")
    s = sorted(xs)
    if len(s) == 1:
        return s[0]
    k = (len(s) - 1) * q / 100.0
    lo, hi = int(k), min(int(k) + 1, len(s) - 1)
    return s[lo] + (s[hi] - s[lo]) * (k - lo)


METRICS = {
    "median_abs_delta": lambda ds: statistics.median([abs(d) for d in ds]),
    "sum_abs_delta":    lambda ds: sum(abs(d) for d in ds),
    "mean_abs_delta":   lambda ds: statistics.fmean([abs(d) for d in ds]),
    "p99_abs_delta":    lambda ds: _percentile([abs(d) for d in ds], 99.0),
    "max_abs_delta":    lambda ds: max(abs(d) for d in ds),
    "median_delta":     lambda ds: statistics.median(ds),
}


def _rank(diff_tsv: Path, metric: str) -> list[tuple[str, float, int]]:
    """Return [(conversation_id, metric_value, n_turns), ...] sorted desc by metric."""
    per_conv: dict[str, list[float]] = defaultdict(list)
    with diff_tsv.open() as f:
        reader = csv.DictReader(f, delimiter="\t")
        for row in reader:
            cid = row["conversation_id"]
            try:
                delta = float(row["ttft_delta_ms"])
            except (ValueError, KeyError):
                continue
            per_conv[cid].append(delta)
    fn = METRICS[metric]
    ranked = [(cid, fn(deltas), len(deltas)) for cid, deltas in per_conv.items() if deltas]
    ranked.sort(key=lambda r: r[1], reverse=True)
    return ranked


def _write_filtered_jsonl(src: Path, dst: Path, keep_cids: set[str]) -> tuple[int, int]:
    """Copy lines from src to dst, keeping only those whose conversation_id is in
    ``keep_cids``. Preserves the original line order (so turns stay contiguous
    and in conversation_idx order, which is how RWLT expects them).
    Returns (kept_lines, total_lines).
    """
    kept = 0
    total = 0
    dst.parent.mkdir(parents=True, exist_ok=True)
    with src.open() as f_in, dst.open("w") as f_out:
        for line in f_in:
            total += 1
            try:
                cid = json.loads(line)["conversation_id"]
            except (json.JSONDecodeError, KeyError):
                continue
            if cid in keep_cids:
                f_out.write(line)
                kept += 1
    return kept, total


CONFIG_TEMPLATE = """\
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Auto-generated by scripts/make_topk_subset.py.
# Source diff TSV : {diff_tsv}
# Ranking metric  : {metric}
# K               : {k}
# Conversations   : {cids}
# Total turns     : {n_turns}

base_url: http://localhost:8000/v1
model: openai/gpt-oss-120b
api_key: not-required

concurrencies: [1]
phase_timeout_seconds: 1800.0
user_spawn_rate: 1.0
settling_time_seconds: 0

min_measurement_seconds: 0.0
min_total_trajectories: {k}
min_trajectories_per_user: {k}

trajectory_path: {trajectory_path}
trajectories_per_user: {k}
max_starting_line_offset: 0
seed: 42

timeout_seconds: 300.0
max_tokens: 16384
reasoning_effort: high

record_err_reasons: true
record_err_reasons_include_input: false
tool_calls_args_only: true
"""


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--diff", required=True, type=Path,
                   help="per-turn diff TSV (output of diff_rwlt_runs.py --per-turn-out)")
    p.add_argument("--k", required=True, type=int,
                   help="number of top conversations to keep")
    p.add_argument("--metric", default="median_abs_delta", choices=sorted(METRICS),
                   help="ranking metric (default: median_abs_delta)")
    p.add_argument("--label", required=True,
                   help="basename for the output config + dataset (no extension). "
                        "Will be referenced as 'rwlt_<label>' in run_session.sh.")
    p.add_argument("--source", default=DEFAULT_SOURCE, type=Path,
                   help="source RWLT JSONL dataset (default: the cookbook scenario file)")
    p.add_argument("--configs-dir", default=Path("configs"), type=Path,
                   help="where to write the rwlt_*.yaml config")
    p.add_argument("--datasets-dir", default=Path("configs/datasets"), type=Path,
                   help="where to write the filtered jsonl")
    args = p.parse_args()

    if not args.diff.is_file():
        print(f"ERROR: diff TSV not found: {args.diff}", file=sys.stderr)
        return 1
    if not args.source.is_file():
        print(f"ERROR: source dataset not found: {args.source}", file=sys.stderr)
        return 1

    ranked = _rank(args.diff, args.metric)
    if len(ranked) < args.k:
        print(f"WARNING: only {len(ranked)} conversations in diff; clamping K={args.k} to {len(ranked)}",
              file=sys.stderr)
        args.k = len(ranked)
    top = ranked[: args.k]

    print(f"# Top {args.k} conversations by {args.metric} from {args.diff}:")
    print(f"  {'rank':<5} {'conversation_id':<35} {'n_turns':>8} {'metric':>12}")
    for i, (cid, val, n) in enumerate(top, start=1):
        print(f"  {i:<5} {cid:<35} {n:>8} {val:>12.3f}")

    keep_cids = {cid for cid, _, _ in top}
    dataset_label = f"{args.label}.jsonl"
    dataset_path = args.datasets_dir / dataset_label
    config_path = args.configs_dir / f"rwlt_{args.label}.yaml"

    kept, total = _write_filtered_jsonl(args.source, dataset_path, keep_cids)
    print(f"\nFiltered dataset: {dataset_path}")
    print(f"  kept {kept} of {total} lines covering {args.k} conversations")

    config_path.write_text(CONFIG_TEMPLATE.format(
        diff_tsv=args.diff.resolve(),
        metric=args.metric,
        k=args.k,
        cids=", ".join(cid for cid, _, _ in top),
        n_turns=kept,
        trajectory_path=dataset_path.resolve(),
    ))
    print(f"RWLT config:      {config_path}")

    print(f"\nRun with (run_session.sh accepts any 'rwlt_*' client name):")
    print(f"  scripts/run_session.sh agg    rwlt_{args.label} agg_{args.label}")
    print(f"  scripts/run_session.sh disagg rwlt_{args.label} disagg_{args.label}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
